spring:
  application:
    name: ${SPRING_APP_NAME:thinksyncsecurity}
  profile:
    activate:
      on-profile: prod
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/thinksyncsecurity
    username: postgres
    password: root
  jpa:
    properties:
      hibernate:
        default_schema: prod
  liquibase:
    default-schema: prod
logging:
  pattern:
    console: ${LOG_PATTERN_CONSOLE:%green(%d{dd-MMM-yyyy HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
  level:
    org:
      springframework:
        security: ERROR
    com:
      thinksync:
        security:
          controller: ERROR

