spring:
  application:
    name: ${SPRING_APP_NAME:thinksyncsecurity}
  profile:
    activate:
      on-profile: dev
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/thinksyncsecurity
    username: postgres
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: public
  liquibase:
    default-schema: public
server:
  servlet:
    session:
      timeout:${SESSION_TIMEOUT:120}  # it is 2min if you want to mention in minute then modify 120 to 2m
logging:
  pattern:
    console: ${LOG_PATTERN_CONSOLE:%green(%d{dd-MMM-yyyy HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
  level:
    org:
      springframework:
        security: DEBUG
    com:
      thinksync:
        security:
          controller: DEBUG
