spring:
  application:
    name: ${SPRING_APP_NAME:thinksyncsecurity}
  profile:
    activate:
      on-profile: qa
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/thinksyncsecurity
    username: postgres
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: qa
  liquibase:
    default-schema: qa
logging:
  pattern:
    console: ${LOG_PATTERN_CONSOLE:%green(%d{dd-MMM-yyyy HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
  level:
    org:
      springframework:
        security: INFO
    com:
      thinksync:
        security:
          controller: INFO
